# Generated by Django 3.2.10 on 2022-01-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_fill_db"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="категория активна"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.CharField(max_length=254, verbose_name="адресс"),
        ),
    ]
